import Head from 'next/head'
import Image from 'next/image'
import CTADownload from '../components/CTADownload'
import FeatureBanking from '../components/FeatureBanking'
import FeaturePayment from '../components/FeaturePayment'
import Features from '../components/Features'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Hero from '../components/Hero'
import Pricing from '../components/Pricing'
import ScanAndPay from '../components/ScanAndPay'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      <Hero/>
      <FeatureBanking/>
      <FeaturePayment/>
      {/* <Features/> */}
      <Pricing/>
      <ScanAndPay/>
      <CTADownload/>
      <Footer/>
    </div>
  )
}
